- zdict/dictionaries/jisho.py
1. add exception of not finding word
2. list "Other forms" of word, and every "english_definitions" of word list the restriction
to some forms of word
3. list "parts of speech" of word
4. list "see also" of "english_definitions" of word
> [#31] improve jisho dict support

- .travis.yml
- setup.cfg
> [travis] change coveralls client

- setup.py
- zdict/tests/test_utils.py
> [testing] skip gnureadline testing on freebsd

- zdict/zdict.py
> Should limit the choices of `-dt/--dict` argument

- zdict/dictionaries/yahoo.py
> [Yahoo dict] Got error when using verbose mode by searching word "accident"

- setup.cfg
- setup.py
- zdict/api.py
- zdict/dictionaries/moe.py
- zdict/dictionaries/template.py
- zdict/dictionaries/urban.py
- zdict/loader.py
- zdict/tests/dictionaries/test_moe.py
- zdict/tests/dictionaries/test_urban.py
- zdict/tests/test_easter_eggs.py
- zdict/tests/test_utils.py
- zdict/utils.py
Let's dicusse our formating criteria here. And doing the format checking in travis.
Ref: https://flake8.readthedocs.org/en/latest/config.html
I will propse that
```ini
max-length = 100
```
Please comment.
> flake8 format checking in ci build

- zdict/tests/test_arguments.py
- zdict/zdict.py
Let zdict support `-j [JOBS]` `--jobs [JOBS]` to query mutiple dictionaries concurrently.
> add multiprocessing support

- zdict/zdict.py
> Use 0 as the argument for -j option causes error

- zdict/tests/test_arguments.py
- zdict/zdict.py
> Interactive prompt with multiprocessing cannot catch `KeyboardInterrupt`

- zdict/dictionaries/jisho.py
- zdict/dictionaries/moe.py
- zdict/dictionaries/spanish.py
- zdict/dictionaries/template.py
- zdict/dictionaries/urban.py
- zdict/dictionaries/yahoo.py
- zdict/dictionary.py
- zdict/loader.py
- zdict/tests/dictionaries/test_jisho.py
- zdict/tests/dictionaries/test_moe.py
- zdict/tests/dictionaries/test_spanish.py
- zdict/tests/dictionaries/test_urban.py
- zdict/tests/dictionaries/test_yahoo.py
- zdict/zdict.py
Add debug mode to pretty print the html response for debugging.
> Add `-D/--debug` mode?

- zdict/dictionaries/yahoo.py
> YahooDict quit unexpectedly while querying the word "relate"

- requirements.txt
- setup.py
- test-requirements.txt
Enhance #95
Use specific verions for every dependency packages.
> Use requirements.txt and test-requirements.txt for setup.py

- .dockerignore
- Dockerfile
- Makefile
- README.rst
- setup.py
- zdict/zdict.py
<https://hub.docker.com/r/zdict/zdict/>
> Add docker support

- .travis.yml
+ https://docs.travis-ci.com/user/deployment/pypi
+ https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on%3A
+ https://github.com/wdv4758h/python-everywhere/blob/master/.travis.yml#L62
> Auto deploying to PyPI when there's a new version.

- README.rst
+ originly => originally
+ integrate => integrates
> [README] Fix some typos.

- README.rst
- zdict/dictionaries/yandex.py
- zdict/tests/dictionaries/test_yandex.py
* https://tech.yandex.com/translate/
* https://tech.yandex.com/dictionary/
> Add Yandex Translate API support

- zdict/constants.py
* [#127] Add Yandex Translate API support
* [#128] Upgrade all dependencies
> [zdict-0.10.0]

- README.rst
> Modify the part related to docker in README for issue-98

- Pipfile
- Pipfile.lock
By "pipenv install -r requirements.txt" and
"pipenv install -d -r test-requirements.txt"
> Add pipenv data

- .pyup.yml
pyup starts to support Pipfile now, let it updates Pipfile too 😄 
Ref: https://github.com/pyupio/pyup/issues/197#issuecomment-360391226
> Open pyup support for Pipfile

- zdict/constants.py
+ Solved issue #130 on GitHub
+ Solved issue #98 on GitHub
+ Added pipenv
+ Use newew version of peewee, coverage, pytest, pyflakes, certifi, py.
ref: <https://github.com/zdict/zdict/compare/v0.10.0...fbbf2d>
> Upgrade version to 0.10.1

- test-requirements.txt
- zdict/dictionaries/template.py
- zdict/dictionaries/yahoo.py
- zdict/dictionary.py
- zdict/loader.py
>  Update flake8 to 3.5.0, pytest-flake8 to 0.9.1

- zdict/dictionaries/yahoo.py
- zdict/tests/dictionaries/test_yahoo.py
> ydict: new format

- zdict/constants.py
* Fix Yahoo dictionary for new format (#195)
* Update peewee to 3.1.5 (#194)
* Update pytest to 3.4.2 (#191)
Ref: https://github.com/zdict/zdict/compare/v0.10.3...f2d4d5e526f6300fb9c15c2d8d8e7a70546acfb2
> Upgrade to v0.11.0

- zdict/dictionaries/spanish.py
- Drop the by-class-name searching because it changes frequently.
- Support more than 1 example sentences
- Change the date structure be saved in to database.
- Cached data for spanish dict will encounter error with this modified show() function.
> [#413] Fix spanish dict

- .circleci/config.yml
- .travis.yml
- setup.py
- Testing environments
- Travis CI
- CircleCI
- Doc
- setup.py
- For description on PyPI.
> [#405] Add python 3.8 support

- zdict/dictionaries/naer.py
provider: 國家教育研究院 - 雙語詞彙、學術名詞暨辭書資訊網
site: https://terms.naer.edu.tw
> Add NAER terms to dictionaries

- .circleci/config.yml
- zdict/dictionaries/apc.py
- zdict/tests/dictionaries/test_apc.py
provider: 原住民族委員會 - 原住民族語言線上詞典
site: https://e-dictionary.apc.gov.tw/
> Add APC e-dictionary to dictionaries (原住民族委員會 - 原住民族語言線上詞典)
